[2023-08-24T04:07:41.762+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline.Vm_pubsub_3M manual__2023-08-24T03:39:47.420172+00:00 [queued]>
[2023-08-24T04:07:41.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline.Vm_pubsub_3M manual__2023-08-24T03:39:47.420172+00:00 [queued]>
[2023-08-24T04:07:41.767+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2023-08-24T04:07:41.778+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Vm_pubsub_3M> on 2023-08-24 03:39:47.420172+00:00
[2023-08-24T04:07:41.781+0000] {standard_task_runner.py:57} INFO - Started process 33406 to run task
[2023-08-24T04:07:41.782+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T04:07:41.788+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline', 'Vm_pubsub_3M', 'manual__2023-08-24T03:39:47.420172+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8nc7r8t6']
[2023-08-24T04:07:41.788+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask Vm_pubsub_3M
[2023-08-24T04:07:41.822+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline.Vm_pubsub_3M manual__2023-08-24T03:39:47.420172+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-24T04:07:41.866+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong' AIRFLOW_CTX_DAG_ID='vnstock-pipeline' AIRFLOW_CTX_TASK_ID='Vm_pubsub_3M' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T03:39:47.420172+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T03:39:47.420172+00:00'
[2023-08-24T04:07:46.779+0000] {logging_mixin.py:151} INFO - root
 |-- Time: timestamp (nullable = true)
 |-- Ticker: string (nullable = true)
 |-- Close: double (nullable = true)
 |-- Percentage_Change: double (nullable = true)
[2023-08-24T04:12:03.472+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-08-24T04:12:03.475+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 33406. PIDs of all processes in the group: [33406]
[2023-08-24T04:12:03.475+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 33406
[2023-08-24T04:12:03.476+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-24T04:12:03.502+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=33406, status='terminated', exitcode=0, started='04:07:41') (33406) terminated with exit code 0
