[2023-08-24T03:57:41.475+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline.Stock_collection_1Y manual__2023-08-24T03:42:40.450293+00:00 [queued]>
[2023-08-24T03:57:41.480+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline.Stock_collection_1Y manual__2023-08-24T03:42:40.450293+00:00 [queued]>
[2023-08-24T03:57:41.480+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-24T03:57:41.492+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Stock_collection_1Y> on 2023-08-24 03:42:40.450293+00:00
[2023-08-24T03:57:41.495+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:57:41.495+0000] {standard_task_runner.py:57} INFO - Started process 29772 to run task
[2023-08-24T03:57:41.502+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline', 'Stock_collection_1Y', 'manual__2023-08-24T03:42:40.450293+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpa07fu658']
[2023-08-24T03:57:41.503+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask Stock_collection_1Y
[2023-08-24T03:57:41.535+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline.Stock_collection_1Y manual__2023-08-24T03:42:40.450293+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-24T03:57:41.554+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-24T03:57:41.555+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:57:41.555+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-08-24T03:57:41.559+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:57:41.583+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong' AIRFLOW_CTX_DAG_ID='vnstock-pipeline' AIRFLOW_CTX_TASK_ID='Stock_collection_1Y' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T03:42:40.450293+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T03:42:40.450293+00:00'
[2023-08-24T03:57:42.398+0000] {logging_mixin.py:151} INFO - 1606/1607_SSI
[2023-08-24T03:57:43.098+0000] {logging_mixin.py:151} INFO - 1605/1607_BCM
[2023-08-24T03:57:43.789+0000] {logging_mixin.py:151} INFO - 1604/1607_VHM
[2023-08-24T03:57:44.473+0000] {logging_mixin.py:151} INFO - 1603/1607_VIC
[2023-08-24T03:57:45.163+0000] {logging_mixin.py:151} INFO - 1602/1607_VRE
[2023-08-24T03:57:45.849+0000] {logging_mixin.py:151} INFO - 1601/1607_BVH
[2023-08-24T03:57:46.547+0000] {logging_mixin.py:151} INFO - 1600/1607_POW
[2023-08-24T03:57:47.244+0000] {logging_mixin.py:151} INFO - 1599/1607_GAS
[2023-08-24T03:57:47.939+0000] {logging_mixin.py:151} INFO - 1598/1607_ACB
[2023-08-24T03:57:48.627+0000] {logging_mixin.py:151} INFO - 1597/1607_BID
[2023-08-24T03:57:49.316+0000] {logging_mixin.py:151} INFO - 1596/1607_CTG
[2023-08-24T03:57:50.007+0000] {logging_mixin.py:151} INFO - 1595/1607_HDB
[2023-08-24T03:57:50.693+0000] {logging_mixin.py:151} INFO - 1594/1607_MBB
[2023-08-24T03:57:51.380+0000] {logging_mixin.py:151} INFO - 1593/1607_SSB
[2023-08-24T03:57:52.113+0000] {logging_mixin.py:151} INFO - 1592/1607_SHB
[2023-08-24T03:57:52.865+0000] {logging_mixin.py:151} INFO - 1591/1607_STB
[2023-08-24T03:57:53.627+0000] {logging_mixin.py:151} INFO - 1590/1607_TCB
[2023-08-24T03:57:54.380+0000] {logging_mixin.py:151} INFO - 1589/1607_TPB
[2023-08-24T03:57:55.137+0000] {logging_mixin.py:151} INFO - 1588/1607_VCB
[2023-08-24T03:57:55.888+0000] {logging_mixin.py:151} INFO - 1587/1607_VIB
[2023-08-24T03:57:56.600+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2023-08-24T03:57:56.604+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 29772. PIDs of all processes in the group: [29772]
[2023-08-24T03:57:56.604+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 29772
[2023-08-24T03:57:56.604+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-24T03:57:56.605+0000] {logging_mixin.py:151} INFO - 1586_error_1607_VPB
[2023-08-24T03:57:56.605+0000] {collect_gcs.py:40} ERROR - message
Traceback (most recent call last):
  File "/home/nguyentuanduong7/airflow/src/pluggin/collect_gcs.py", line 29, in stock_collection_1Y
    stock_data=stock_historical_data (symbol=stock, start_date=start_date, end_date=current_date, resolution=resolution, type='stock')
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/vnstock/stock.py", line 148, in stock_historical_data
    df = stock_ohlc(symbol, start_date, end_date, resolution, type, headers)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/vnstock/stock.py", line 178, in stock_ohlc
    response = requests.request("GET", url, headers=headers).json()
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1821, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-08-24T03:57:57.361+0000] {logging_mixin.py:151} INFO - 1585/1607_HPG
[2023-08-24T03:57:58.096+0000] {logging_mixin.py:151} INFO - 1584/1607_GVR
[2023-08-24T03:57:58.850+0000] {logging_mixin.py:151} INFO - 1583/1607_MSN
[2023-08-24T03:57:59.611+0000] {logging_mixin.py:151} INFO - 1582/1607_VNM
[2023-08-24T03:58:00.369+0000] {logging_mixin.py:151} INFO - 1581/1607_SAB
[2023-08-24T03:58:01.116+0000] {logging_mixin.py:151} INFO - 1580/1607_VJC
[2023-08-24T03:58:01.859+0000] {logging_mixin.py:151} INFO - 1579/1607_MWG
[2023-08-24T03:58:02.614+0000] {logging_mixin.py:151} INFO - 1578/1607_PLX
[2023-08-24T03:58:03.374+0000] {logging_mixin.py:151} INFO - 1577/1607_FPT
[2023-08-24T03:58:04.113+0000] {logging_mixin.py:151} INFO - 1576/1607_MFS
[2023-08-24T03:58:04.862+0000] {logging_mixin.py:151} INFO - 1575/1607_ABC
[2023-08-24T03:58:05.616+0000] {logging_mixin.py:151} INFO - 1574/1607_VGI
[2023-08-24T03:58:06.391+0000] {logging_mixin.py:151} INFO - 1573/1607_FOX
[2023-08-24T03:58:07.144+0000] {logging_mixin.py:151} INFO - 1572/1607_PAI
[2023-08-24T03:58:07.896+0000] {logging_mixin.py:151} INFO - 1571/1607_PIA
[2023-08-24T03:58:08.648+0000] {logging_mixin.py:151} INFO - 1570/1607_PTP
[2023-08-24T03:58:09.402+0000] {logging_mixin.py:151} INFO - 1569/1607_TTN
[2023-08-24T03:58:10.156+0000] {logging_mixin.py:151} INFO - 1568/1607_FUCTVGF3
[2023-08-24T03:58:10.903+0000] {logging_mixin.py:151} INFO - 1567/1607_FUEIP100
[2023-08-24T03:58:11.644+0000] {logging_mixin.py:151} INFO - 1566/1607_FUEKIV30
[2023-08-24T03:58:12.394+0000] {logging_mixin.py:151} INFO - 1565/1607_FUCTVGF4
[2023-08-24T03:58:13.150+0000] {logging_mixin.py:151} INFO - 1564/1607_FUEDCMID
[2023-08-24T03:58:13.898+0000] {logging_mixin.py:151} INFO - 1563/1607_FUEKIVFS
[2023-08-24T03:58:14.650+0000] {logging_mixin.py:151} INFO - 1562/1607_FUEMAVND
[2023-08-24T03:58:15.392+0000] {logging_mixin.py:151} INFO - 1561/1607_FUEFCV50
[2023-08-24T03:58:16.136+0000] {logging_mixin.py:151} INFO - 1560/1607_FUEBFVND
[2023-08-24T03:58:16.896+0000] {logging_mixin.py:151} INFO - 1559/1607_FUESSV50
[2023-08-24T03:58:17.648+0000] {logging_mixin.py:151} INFO - 1558/1607_E1VFVN30
[2023-08-24T03:58:18.412+0000] {logging_mixin.py:151} INFO - 1557/1607_FUESSVFL
[2023-08-24T03:58:18.415+0000] {python.py:194} INFO - Done. Returned value was: Done
[2023-08-24T03:58:18.428+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=vnstock-pipeline, task_id=Stock_collection_1Y, execution_date=20230824T034240, start_date=20230824T035741, end_date=20230824T035818
[2023-08-24T03:58:18.472+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=29772, status='terminated', exitcode=0, started='03:57:40') (29772) terminated with exit code 0
